services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rising_stars_app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://rising_stars_user:rising_stars_password@10.0.0.118:5432/rising_stars_db
      - SECRET_KEY=your-secret-key
    ports:
      - "8000:8000"
      - "4444:4444"
    networks:
      - app-network
    volumes:
      - ./app:/app/app
      - ./videos:/app/videos
      - /mnt/nfs-data:/mnt/nfs-data

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
